#!/bin/sh

rm -f config.log
rm -f config.status
rm -rf autom4te.cache
rm -f local.zip
rm -f gsl.zip
rm -f src/Makevars
rm -f src/*.o
rm -f src/core/*.o
rm -f src/events/*.o
rm -f src/misc/*.o
rm -f src/models/*.o
rm -f src/*.so
rm -rf src-x64
rm -rf src-i386
rm -rf gsl
rm -rf src/gsl
rm vignettes/SimInf.aux
rm vignettes/SimInf.bbl
rm vignettes/SimInf.blg
rm vignettes/SimInf.log
rm vignettes/SimInf.out
rm vignettes/SimInf.pdf
