## Generate C code to register functions to be called from R
## See the "Writing R Extensions":
## https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Registering-native-routines

## List all models
files <- list.files(path = "src/models", pattern = ".c$")
models <- tools::file_path_sans_ext(files)

lines <- c(
    "/* Generated by tools/init.R: do not edit by hand */",
    "",
    "#include <Rdefines.h>",
    "#include <R_ext/Rdynload.h>",
    "#include <R_ext/Visibility.h>",
    "",
    "/* Declare functions to register */",
    paste0("SEXP ", models, "_run(SEXP, SEXP, SEXP);"),
    "SEXP siminf_ldata_sp(SEXP, SEXP, SEXP);",
    "SEXP siminf_have_openmp();",
    "",
    "static const R_CallMethodDef callMethods[] =",
    "{",
    paste0("    {\"", models, "_run\", (DL_FUNC) &", models, "_run, 3},"),
    "    {\"siminf_have_openmp\", (DL_FUNC) &siminf_have_openmp, 0},",
    "    {\"siminf_ldata_sp\", (DL_FUNC) &siminf_ldata_sp, 3},",
    "    {NULL, NULL, 0}",
    "};",
    "",
    "void attribute_visible",
    "R_init_SimInf(DllInfo *info)",
    "{",
    "    R_registerRoutines(info, NULL, callMethods, NULL, NULL);",
    "    R_useDynamicSymbols(info, FALSE);",
    "    R_forceSymbols(info, FALSE);",
    "}",
    "")

f <- file("src/init.c", "wb")
writeChar(paste0(lines, collapse = "\n"), f, eos = NULL)
close(f)
